/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SubscriptionErrorCause the model 'SubscriptionErrorCause'
type SubscriptionErrorCause string

// List of SubscriptionErrorCause
const (
	PROVISIONING_JENKINS SubscriptionErrorCause = "PROVISIONING_JENKINS"
	CIS SubscriptionErrorCause = "CIS"
	DESTROYING_JENKINS SubscriptionErrorCause = "DESTROYING_JENKINS"
	PROVISIONING_DB SubscriptionErrorCause = "PROVISIONING_DB"
	DESTROYING_DB SubscriptionErrorCause = "DESTROYING_DB"
)

// All allowed values of SubscriptionErrorCause enum
var AllowedSubscriptionErrorCauseEnumValues = []SubscriptionErrorCause{
	"PROVISIONING_JENKINS",
	"CIS",
	"DESTROYING_JENKINS",
	"PROVISIONING_DB",
	"DESTROYING_DB",
}

func (v *SubscriptionErrorCause) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubscriptionErrorCause(value)
	for _, existing := range AllowedSubscriptionErrorCauseEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubscriptionErrorCause", value)
}

// NewSubscriptionErrorCauseFromValue returns a pointer to a valid SubscriptionErrorCause
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubscriptionErrorCauseFromValue(v string) (*SubscriptionErrorCause, error) {
	ev := SubscriptionErrorCause(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubscriptionErrorCause: valid values are %v", v, AllowedSubscriptionErrorCauseEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubscriptionErrorCause) IsValid() bool {
	for _, existing := range AllowedSubscriptionErrorCauseEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubscriptionErrorCause value
func (v SubscriptionErrorCause) Ptr() *SubscriptionErrorCause {
	return &v
}

type NullableSubscriptionErrorCause struct {
	value *SubscriptionErrorCause
	isSet bool
}

func (v NullableSubscriptionErrorCause) Get() *SubscriptionErrorCause {
	return v.value
}

func (v *NullableSubscriptionErrorCause) Set(val *SubscriptionErrorCause) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionErrorCause) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionErrorCause) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionErrorCause(val *SubscriptionErrorCause) *NullableSubscriptionErrorCause {
	return &NullableSubscriptionErrorCause{value: val, isSet: true}
}

func (v NullableSubscriptionErrorCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionErrorCause) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

