/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GitProvider the model 'GitProvider'
type GitProvider string

// List of GitProvider
const (
	GITHUB GitProvider = "GITHUB"
	BITBUCKET GitProvider = "BITBUCKET"
	BITBUCKET_CLOUD GitProvider = "BITBUCKET_CLOUD"
)

// All allowed values of GitProvider enum
var AllowedGitProviderEnumValues = []GitProvider{
	"GITHUB",
	"BITBUCKET",
	"BITBUCKET_CLOUD",
}

func (v *GitProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitProvider(value)
	for _, existing := range AllowedGitProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitProvider", value)
}

// NewGitProviderFromValue returns a pointer to a valid GitProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitProviderFromValue(v string) (*GitProvider, error) {
	ev := GitProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitProvider: valid values are %v", v, AllowedGitProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitProvider) IsValid() bool {
	for _, existing := range AllowedGitProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GitProvider value
func (v GitProvider) Ptr() *GitProvider {
	return &v
}

type NullableGitProvider struct {
	value *GitProvider
	isSet bool
}

func (v NullableGitProvider) Get() *GitProvider {
	return v.value
}

func (v *NullableGitProvider) Set(val *GitProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableGitProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableGitProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitProvider(val *GitProvider) *NullableGitProvider {
	return &NullableGitProvider{value: val, isSet: true}
}

func (v NullableGitProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

