/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatedSubscription struct for CreatedSubscription
type CreatedSubscription struct {
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Email string `json:"email"`
	Function string `json:"function"`
	Company string `json:"company"`
	Password string `json:"password"`
	Country string `json:"country"`
	PlanId *string `json:"planId,omitempty"`
}

// NewCreatedSubscription instantiates a new CreatedSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedSubscription(firstName string, lastName string, email string, function string, company string, password string, country string) *CreatedSubscription {
	this := CreatedSubscription{}
	this.FirstName = firstName
	this.LastName = lastName
	this.Email = email
	this.Function = function
	this.Company = company
	this.Password = password
	this.Country = country
	return &this
}

// NewCreatedSubscriptionWithDefaults instantiates a new CreatedSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedSubscriptionWithDefaults() *CreatedSubscription {
	this := CreatedSubscription{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *CreatedSubscription) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetFirstNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *CreatedSubscription) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *CreatedSubscription) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetLastNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *CreatedSubscription) SetLastName(v string) {
	o.LastName = v
}

// GetEmail returns the Email field value
func (o *CreatedSubscription) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreatedSubscription) SetEmail(v string) {
	o.Email = v
}

// GetFunction returns the Function field value
func (o *CreatedSubscription) GetFunction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Function
}

// GetFunctionOk returns a tuple with the Function field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetFunctionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Function, true
}

// SetFunction sets field value
func (o *CreatedSubscription) SetFunction(v string) {
	o.Function = v
}

// GetCompany returns the Company field value
func (o *CreatedSubscription) GetCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetCompanyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *CreatedSubscription) SetCompany(v string) {
	o.Company = v
}

// GetPassword returns the Password field value
func (o *CreatedSubscription) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreatedSubscription) SetPassword(v string) {
	o.Password = v
}

// GetCountry returns the Country field value
func (o *CreatedSubscription) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetCountryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *CreatedSubscription) SetCountry(v string) {
	o.Country = v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *CreatedSubscription) GetPlanId() string {
	if o == nil || o.PlanId == nil {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedSubscription) GetPlanIdOk() (*string, bool) {
	if o == nil || o.PlanId == nil {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *CreatedSubscription) HasPlanId() bool {
	if o != nil && o.PlanId != nil {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *CreatedSubscription) SetPlanId(v string) {
	o.PlanId = &v
}

func (o CreatedSubscription) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["firstName"] = o.FirstName
	}
	if true {
		toSerialize["lastName"] = o.LastName
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["function"] = o.Function
	}
	if true {
		toSerialize["company"] = o.Company
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if true {
		toSerialize["country"] = o.Country
	}
	if o.PlanId != nil {
		toSerialize["planId"] = o.PlanId
	}
	return json.Marshal(toSerialize)
}

type NullableCreatedSubscription struct {
	value *CreatedSubscription
	isSet bool
}

func (v NullableCreatedSubscription) Get() *CreatedSubscription {
	return v.value
}

func (v *NullableCreatedSubscription) Set(val *CreatedSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedSubscription(val *CreatedSubscription) *NullableCreatedSubscription {
	return &NullableCreatedSubscription{value: val, isSet: true}
}

func (v NullableCreatedSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


