/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SubscriptionStatus the model 'SubscriptionStatus'
type SubscriptionStatus string

// List of SubscriptionStatus
const (
	CREATED SubscriptionStatus = "CREATED"
	PROVISIONING SubscriptionStatus = "PROVISIONING"
	ACTIVE SubscriptionStatus = "ACTIVE"
	INACTIVE SubscriptionStatus = "INACTIVE"
	ERROR SubscriptionStatus = "ERROR"
	DESTROYING SubscriptionStatus = "DESTROYING"
	UPDATING SubscriptionStatus = "UPDATING"
	UPDATE_ERROR SubscriptionStatus = "UPDATE_ERROR"
)

// All allowed values of SubscriptionStatus enum
var AllowedSubscriptionStatusEnumValues = []SubscriptionStatus{
	"CREATED",
	"PROVISIONING",
	"ACTIVE",
	"INACTIVE",
	"ERROR",
	"DESTROYING",
	"UPDATING",
	"UPDATE_ERROR",
}

func (v *SubscriptionStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubscriptionStatus(value)
	for _, existing := range AllowedSubscriptionStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubscriptionStatus", value)
}

// NewSubscriptionStatusFromValue returns a pointer to a valid SubscriptionStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubscriptionStatusFromValue(v string) (*SubscriptionStatus, error) {
	ev := SubscriptionStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubscriptionStatus: valid values are %v", v, AllowedSubscriptionStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubscriptionStatus) IsValid() bool {
	for _, existing := range AllowedSubscriptionStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubscriptionStatus value
func (v SubscriptionStatus) Ptr() *SubscriptionStatus {
	return &v
}

type NullableSubscriptionStatus struct {
	value *SubscriptionStatus
	isSet bool
}

func (v NullableSubscriptionStatus) Get() *SubscriptionStatus {
	return v.value
}

func (v *NullableSubscriptionStatus) Set(val *SubscriptionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionStatus(val *SubscriptionStatus) *NullableSubscriptionStatus {
	return &NullableSubscriptionStatus{value: val, isSet: true}
}

func (v NullableSubscriptionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

