/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MetricAllOf struct for MetricAllOf
type MetricAllOf struct {
	Id string `json:"id"`
}

// NewMetricAllOf instantiates a new MetricAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricAllOf(id string) *MetricAllOf {
	this := MetricAllOf{}
	this.Id = id
	return &this
}

// NewMetricAllOfWithDefaults instantiates a new MetricAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricAllOfWithDefaults() *MetricAllOf {
	this := MetricAllOf{}
	return &this
}

// GetId returns the Id field value
func (o *MetricAllOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MetricAllOf) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MetricAllOf) SetId(v string) {
	o.Id = v
}

func (o MetricAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableMetricAllOf struct {
	value *MetricAllOf
	isSet bool
}

func (v NullableMetricAllOf) Get() *MetricAllOf {
	return v.value
}

func (v *NullableMetricAllOf) Set(val *MetricAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricAllOf(val *MetricAllOf) *NullableMetricAllOf {
	return &NullableMetricAllOf{value: val, isSet: true}
}

func (v NullableMetricAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


