/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IdentityProviderData struct for IdentityProviderData
type IdentityProviderData struct {
	UserGroupId *string `json:"userGroupId,omitempty"`
}

// NewIdentityProviderData instantiates a new IdentityProviderData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityProviderData() *IdentityProviderData {
	this := IdentityProviderData{}
	return &this
}

// NewIdentityProviderDataWithDefaults instantiates a new IdentityProviderData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityProviderDataWithDefaults() *IdentityProviderData {
	this := IdentityProviderData{}
	return &this
}

// GetUserGroupId returns the UserGroupId field value if set, zero value otherwise.
func (o *IdentityProviderData) GetUserGroupId() string {
	if o == nil || o.UserGroupId == nil {
		var ret string
		return ret
	}
	return *o.UserGroupId
}

// GetUserGroupIdOk returns a tuple with the UserGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProviderData) GetUserGroupIdOk() (*string, bool) {
	if o == nil || o.UserGroupId == nil {
		return nil, false
	}
	return o.UserGroupId, true
}

// HasUserGroupId returns a boolean if a field has been set.
func (o *IdentityProviderData) HasUserGroupId() bool {
	if o != nil && o.UserGroupId != nil {
		return true
	}

	return false
}

// SetUserGroupId gets a reference to the given string and assigns it to the UserGroupId field.
func (o *IdentityProviderData) SetUserGroupId(v string) {
	o.UserGroupId = &v
}

func (o IdentityProviderData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserGroupId != nil {
		toSerialize["userGroupId"] = o.UserGroupId
	}
	return json.Marshal(toSerialize)
}

type NullableIdentityProviderData struct {
	value *IdentityProviderData
	isSet bool
}

func (v NullableIdentityProviderData) Get() *IdentityProviderData {
	return v.value
}

func (v *NullableIdentityProviderData) Set(val *IdentityProviderData) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityProviderData) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityProviderData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityProviderData(val *IdentityProviderData) *NullableIdentityProviderData {
	return &NullableIdentityProviderData{value: val, isSet: true}
}

func (v NullableIdentityProviderData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityProviderData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


