/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdatePlanRequest struct for UpdatePlanRequest
type UpdatePlanRequest struct {
	PlanId string `json:"planId"`
}

// NewUpdatePlanRequest instantiates a new UpdatePlanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlanRequest(planId string) *UpdatePlanRequest {
	this := UpdatePlanRequest{}
	this.PlanId = planId
	return &this
}

// NewUpdatePlanRequestWithDefaults instantiates a new UpdatePlanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlanRequestWithDefaults() *UpdatePlanRequest {
	this := UpdatePlanRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *UpdatePlanRequest) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *UpdatePlanRequest) GetPlanIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *UpdatePlanRequest) SetPlanId(v string) {
	o.PlanId = v
}

func (o UpdatePlanRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["planId"] = o.PlanId
	}
	return json.Marshal(toSerialize)
}

type NullableUpdatePlanRequest struct {
	value *UpdatePlanRequest
	isSet bool
}

func (v NullableUpdatePlanRequest) Get() *UpdatePlanRequest {
	return v.value
}

func (v *NullableUpdatePlanRequest) Set(val *UpdatePlanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlanRequest(val *UpdatePlanRequest) *NullableUpdatePlanRequest {
	return &NullableUpdatePlanRequest{value: val, isSet: true}
}

func (v NullableUpdatePlanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


