/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvitationEmails You can invite multiple users together. The users will be assigned to the input group.
type InvitationEmails struct {
	// A set of emails, used e.g. for invitations or reactivation.
	Emails []string `json:"emails"`
	Group string `json:"group"`
}

// NewInvitationEmails instantiates a new InvitationEmails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationEmails(emails []string, group string) *InvitationEmails {
	this := InvitationEmails{}
	this.Emails = emails
	this.Group = group
	return &this
}

// NewInvitationEmailsWithDefaults instantiates a new InvitationEmails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationEmailsWithDefaults() *InvitationEmails {
	this := InvitationEmails{}
	return &this
}

// GetEmails returns the Emails field value
func (o *InvitationEmails) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *InvitationEmails) GetEmailsOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *InvitationEmails) SetEmails(v []string) {
	o.Emails = v
}

// GetGroup returns the Group field value
func (o *InvitationEmails) GetGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *InvitationEmails) GetGroupOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *InvitationEmails) SetGroup(v string) {
	o.Group = v
}

func (o InvitationEmails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["emails"] = o.Emails
	}
	if true {
		toSerialize["group"] = o.Group
	}
	return json.Marshal(toSerialize)
}

type NullableInvitationEmails struct {
	value *InvitationEmails
	isSet bool
}

func (v NullableInvitationEmails) Get() *InvitationEmails {
	return v.value
}

func (v *NullableInvitationEmails) Set(val *InvitationEmails) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationEmails) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationEmails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationEmails(val *InvitationEmails) *NullableInvitationEmails {
	return &NullableInvitationEmails{value: val, isSet: true}
}

func (v NullableInvitationEmails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationEmails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


