/*
Subscription Service Endpoints

## Create subscription  Create a new subscription.  ``` curl -v -d '{\\     \"company\": \"My Company\", \\     \"firstName\": \"First\", \\     \"lastName\": \"Last\", \\     \"email\": \"first.last@magnolia-cms.com\", \\     \"password\": \"some1%2Tres\", \\     \"function\": \"CTO\", \\     \"country\": \"Spain\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/public/subscriptions\" ``` ## Update subscription  Update a new subscription. This is an idempotent operation.  ``` curl -v -d '{\\     \"id\": \"my-company\" \\     }' \\ -H \"Content-Type: application/json\" -X POST \"http://localhost:8080/admin/subscriptions/{subId}\" ``` ## Invite users  Invite a list of users to a subscription.  ## Validate invitation  Validate an invitation to a subscription.  ## Activate user  Activate a user for a subscription. The user needs an invitation to be activated. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GitConfigurationPrivateResponse struct for GitConfigurationPrivateResponse
type GitConfigurationPrivateResponse struct {
	GitSecret *string `json:"gitSecret,omitempty"`
	GitCloneUrl *string `json:"gitCloneUrl,omitempty"`
}

// NewGitConfigurationPrivateResponse instantiates a new GitConfigurationPrivateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitConfigurationPrivateResponse() *GitConfigurationPrivateResponse {
	this := GitConfigurationPrivateResponse{}
	return &this
}

// NewGitConfigurationPrivateResponseWithDefaults instantiates a new GitConfigurationPrivateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitConfigurationPrivateResponseWithDefaults() *GitConfigurationPrivateResponse {
	this := GitConfigurationPrivateResponse{}
	return &this
}

// GetGitSecret returns the GitSecret field value if set, zero value otherwise.
func (o *GitConfigurationPrivateResponse) GetGitSecret() string {
	if o == nil || o.GitSecret == nil {
		var ret string
		return ret
	}
	return *o.GitSecret
}

// GetGitSecretOk returns a tuple with the GitSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitConfigurationPrivateResponse) GetGitSecretOk() (*string, bool) {
	if o == nil || o.GitSecret == nil {
		return nil, false
	}
	return o.GitSecret, true
}

// HasGitSecret returns a boolean if a field has been set.
func (o *GitConfigurationPrivateResponse) HasGitSecret() bool {
	if o != nil && o.GitSecret != nil {
		return true
	}

	return false
}

// SetGitSecret gets a reference to the given string and assigns it to the GitSecret field.
func (o *GitConfigurationPrivateResponse) SetGitSecret(v string) {
	o.GitSecret = &v
}

// GetGitCloneUrl returns the GitCloneUrl field value if set, zero value otherwise.
func (o *GitConfigurationPrivateResponse) GetGitCloneUrl() string {
	if o == nil || o.GitCloneUrl == nil {
		var ret string
		return ret
	}
	return *o.GitCloneUrl
}

// GetGitCloneUrlOk returns a tuple with the GitCloneUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitConfigurationPrivateResponse) GetGitCloneUrlOk() (*string, bool) {
	if o == nil || o.GitCloneUrl == nil {
		return nil, false
	}
	return o.GitCloneUrl, true
}

// HasGitCloneUrl returns a boolean if a field has been set.
func (o *GitConfigurationPrivateResponse) HasGitCloneUrl() bool {
	if o != nil && o.GitCloneUrl != nil {
		return true
	}

	return false
}

// SetGitCloneUrl gets a reference to the given string and assigns it to the GitCloneUrl field.
func (o *GitConfigurationPrivateResponse) SetGitCloneUrl(v string) {
	o.GitCloneUrl = &v
}

func (o GitConfigurationPrivateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GitSecret != nil {
		toSerialize["gitSecret"] = o.GitSecret
	}
	if o.GitCloneUrl != nil {
		toSerialize["gitCloneUrl"] = o.GitCloneUrl
	}
	return json.Marshal(toSerialize)
}

type NullableGitConfigurationPrivateResponse struct {
	value *GitConfigurationPrivateResponse
	isSet bool
}

func (v NullableGitConfigurationPrivateResponse) Get() *GitConfigurationPrivateResponse {
	return v.value
}

func (v *NullableGitConfigurationPrivateResponse) Set(val *GitConfigurationPrivateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGitConfigurationPrivateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGitConfigurationPrivateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitConfigurationPrivateResponse(val *GitConfigurationPrivateResponse) *NullableGitConfigurationPrivateResponse {
	return &NullableGitConfigurationPrivateResponse{value: val, isSet: true}
}

func (v NullableGitConfigurationPrivateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitConfigurationPrivateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


